voteagora/op-atlas

src/components/dashboard/ProfileDetailCard.tsx
src/components/dialogs/AppDialogs.tsx
src/components/dialogs/EditProfileDialog.tsx
src/components/dialogs/types.ts

feat: Add "edit profile" dialog

---

public/assets/icons/plus.svg
src/components/dashboard/AddFirstProjectSection.tsx
src/components/dashboard/ProfileDetailCard.tsx
src/components/dashboard/index.tsx

just doin a little refresh of the styles to match the latest figma

feat: fix style for profile page

---

src/components/dashboard/ProfileDetailCard.tsx
src/components/dialogs/AppDialogs.tsx
src/components/dialogs/EditProfileDialog.tsx
src/components/dialogs/EmailDialog.tsx
src/components/dialogs/types.ts

ugh got lost when the base branch for my second PR didn't update to main

feat: Edit profile dialog (copy)

---

.eslintrc.json
.gitignore
package.json
prisma/schema.prisma
src/app/api/auth/[...nextauth]/route.ts
src/app/application/page.tsx
src/app/dashboard/page.tsx
src/app/globals.css
src/app/page.tsx
src/app/projects/layout.tsx
src/app/signin/page.tsx
src/auth.ts
src/components/common/Account.tsx
src/components/dashboard/AddFirstProjectSection.tsx
src/components/dashboard/ApplyRetroFundingRoundInfoBanner.tsx
src/components/dashboard/ProfileDetailCard.tsx
src/components/dashboard/index.tsx
src/db/client.ts
src/db/users.ts
src/lib/utils.ts
yarn.lock

Note: this is stacked on top of #6, so I'll rebase after it's merged
- Upgrade to next auth 5 (much more ergonomic API and might help with stability)
- Persist users to our database upon signing in
- Wire up the dashboard page with the currently signed in user's profile
- Various other styling/UI fixes for dashboard

Next auth upgrade and live profile data

---

package.json
src/app/projects/new/page.tsx
src/components/projects/details/AddProjectDetailsForm.tsx
src/components/projects/details/CategoryDefinitions.tsx
src/components/ui/accordion.tsx
yarn.lock

feat: Project details part 2 - add category definitions + twitter/mirror links

---

src/components/projects/details/ProjectDetailsForm.tsx

feat: multiple websites + farcasters in project details

---

package.json
src/components/common/FileUploadInput.tsx
src/components/dialogs/EditProfileDialog.tsx
src/components/dialogs/EmailDialog.tsx
src/components/dialogs/types.ts
src/components/projects/details/PhotoCropModal.tsx
src/components/projects/details/ProjectDetailsForm.tsx
yarn.lock

feat: Add photo cropping modal

---

src/app/projects/[projectId]/layout.tsx
src/app/projects/new/page.tsx
src/components/projects/ProjectSidebar.tsx

feat: bold current page in sidebar

---

src/components/projects/contracts/ContractForm.tsx
src/components/ui/dropdown-menu.tsx

feat: Contracts page part 5 - add verified contract actions

---

src/app/dashboard/page.tsx
src/app/projects/[projectId]/layout.tsx
src/auth.ts
src/components/projects/DeleteProjectDialog.tsx
src/components/projects/ProjectSidebar.tsx
src/components/projects/contracts/ContractForm.tsx
src/components/projects/contracts/VerifyAddressDialog.tsx
src/lib/actions/projects.ts
src/lib/actions/users.ts
src/lib/hooks.ts

feat: Add delete project and fix user id stuff

---

src/components/common/Account.tsx

fix: Issue with always redirecting back to dashboard

---

prisma/schema.prisma
src/app/application/page.tsx
src/app/dashboard/page.tsx
src/app/projects/[projectId]/publish/page.tsx
src/app/projects/new/page.tsx
src/app/welcome/page.tsx
src/components/application/ApplicationStatus.tsx
src/components/application/ApplicationSubmitted.tsx
src/components/application/FundingApplication.tsx
src/components/application/ProjectCard.tsx
src/components/application/index.tsx
src/components/common/Badge.tsx
src/components/common/Callout.tsx
src/components/dashboard/ApplicationBanner.tsx
src/components/dashboard/index.tsx
src/components/projects/publish/Snapshot.tsx
src/db/projects.ts
src/lib/actions/applications.ts
src/lib/actions/contracts.ts
src/lib/actions/projects.ts
src/lib/utils/index.ts

Able to apply with projects! A follow-up will plumb this data into the applications page so that you can't re-apply

Applications pt 1

---

src/app/globals.css
src/components/application/ApplicationStatus.tsx
src/components/application/ApplicationSubmitted.tsx
src/components/application/FundingApplication.tsx
src/components/application/ProjectCard.tsx
src/components/application/index.tsx
src/components/projects/details/ProjectDetailsForm.tsx
tailwind.config.ts

The application and application submission page both use real data now, and you can't repeat apply anymore. Still need an understanding from the OP team of whether applying with multiple projects is allowed.

Finish application handling

---

src/app/welcome/page.tsx
src/components/dialogs/GetStartedDialog.tsx
src/components/home/Sidebar.tsx
src/lib/actions/utils.ts
src/lib/utils/index.ts

feat: Add get started dialog

---

src/components/ui/button.tsx
src/components/ui/command.tsx
src/components/ui/select.tsx

hover states are all either bg-secondary or opacity-80 now

fix: hover states

---

src/lib/github.ts

This gets us much higher rate limits from the GH API

Use GH auth token from env

---

src/components/application/ApplicationSubmitted.tsx
src/components/application/FundingApplication.tsx
src/components/application/ProjectCard.tsx

- Allows people to return to the application page and submit another project
- You can only apply with one project at a time via the form (pending design approval)

Handle multiple applications

---

src/components/common/Account.tsx
src/components/common/Navbar.tsx

feat: add navbar dropdown

---

src/components/home/FundingRounds.tsx

the funding round cards should have different parent elements depending on its behavior
- funding round now: button
- funding round with links: ExternalLink
- funding round without links: div

feat: fix funding round links

---

src/components/common/chain.ts
src/components/projects/contracts/VerifyAddressDialog.tsx
src/lib/actions/contracts.ts
src/lib/actions/snapshots.ts
src/lib/eth.ts
src/lib/utils/contracts.ts

Integrate tx traces for create2 contract verification

---

src/components/application/FundingApplication.tsx
src/components/common/Account.tsx
src/components/dashboard/ApplicationBanner.tsx
src/components/dashboard/index.tsx
src/components/projects/details/ProjectDetailsForm.tsx
src/components/projects/publish/PublishForm.tsx
src/components/projects/teams/AddTeamMemberDialog.tsx
src/components/projects/teams/TeamForm.tsx
src/components/ui/multiselectautocomplete.tsx
src/providers/AnalyticsProvider.tsx

reference: https://docs.google.com/document/d/1vohZ9FPWoEi2P6Gdp5Wdoa0IrOhtzEcJLb1G0Yv7VzA/edit?pli=1

feat: add mixpanel events

---

src/components/common/Navbar.tsx
src/components/home/Rounds.tsx

- Cap the width of the content within the nav bar so it looks good on big screens
- Size and position the background image correctly

Some UI cleanup for the homepage

---

src/components/projects/grants/FundingForm.tsx
src/components/projects/grants/GrantsForm.tsx

feat: Grants copy and callout

---

src/components/projects/teams/AddTeamMemberDialog.tsx

fix: Ignore @ when searching by username

---

src/components/dashboard/ProjectRewardRow.tsx
src/components/dashboard/index.tsx

feat: show rewards on dashboard

---

src/app/projects/[projectId]/rewards/page.tsx
src/components/dashboard/ProjectRewardRow.tsx
src/components/dashboard/index.tsx
src/components/projects/ProjectStatusSidebar.tsx
src/components/projects/rewards/RewardsSection.tsx

feat: project rewards page

---

src/components/rewards/ClaimForm.tsx
src/components/rewards/RewardClaimFlow.tsx
src/lib/rewards.ts

feat: claim form on rewards page

---

src/app/api/v1/projects/[projectId]/metadata_snapshot/route.ts
src/db/projects.ts
src/lib/utils/metadata.ts

https://github.com/voteagora/op-atlas/issues/208

:bug: add missing github & packages metadata

---

src/components/application/6/ProjectImpactForm.tsx

fixed typo on impact statement form

---

prisma/migrations/20241011172426_adds_grant_eligibility_claim_at_field_to_reward_claim/migration.sql
prisma/schema.prisma
src/app/api/webhook/updateClaimEligibility/route.ts
src/components/rewards/ClaimForm.tsx
src/db/rewards.ts
src/lib/actions/rewards.ts

Todo: 
- hookup API endpoint to webhook in zapier
- figure out logic for when a KYC is "in progress" so we can show pending copy (ready to go, just need logic)

Adds new claim step

---

src/components/dashboard/index.tsx
src/components/home/FundingRounds.tsx
src/lib/mocks.ts

Merge when we are ready to close apps 
also remember to set NEXT_PUBLIC_APPLICATIONS_CLOSED env var to true, and do a new build

Closes r6 applications

---

app/src/components/common/Navbar.tsx

Removed max-width on nav bar.
If on public profile, hide tabs on nav bar.
If on public profile, set nav bar background color to primary color.
if on public profile, remove shadow from nav bar.
Satisfies https://github.com/voteagora/op-atlas/issues/362.

Nav Bar Modifications

---

app/src/components/common/OutboundArrowLink.tsx
app/src/components/profile/public/ProfileRoles.tsx

Satisfies https://github.com/voteagora/op-atlas/issues/400.

Public Profile - Attestation Cards Default View and Hover States

---

app/src/auth.ts

Reverts voteagora/op-atlas#442
Reverting by now as this setup requests access by the bot account and might raise suspicion

Revert "try fix: Connect Github: Be Careful"

---

app/src/components/profile/GithubConnection.tsx

Updates the subtext for Github on the connected apps page.
Satisifies https://github.com/voteagora/op-atlas/issues/448.

Dashboard/Connected Apps - Github Subtext update

---

app/src/components/projects/repos/ReposForm.tsx

Issue: https://github.com/voteagora/op-atlas/issues/393
**NOTE**: I noticed that the state for project repos form is not updated either so I included that one too as part of this PR.

fix(issue-393): reset form with new data on save

---

app/src/app/globals.css
app/src/app/profile/details/page.tsx
app/src/app/profile/verified-addresses/content.tsx
app/src/app/profile/verified-addresses/verified-address.tsx
app/src/components/common/Account.tsx
app/src/components/common/Button.tsx
app/src/components/common/DropdownItem.tsx
app/src/components/common/ExtendedLink.tsx
app/src/components/common/Navbar.tsx
app/src/components/dialogs/EmailDialog.tsx
app/src/components/home/FundingRounds.tsx
app/src/components/icons/checkIconRed.tsx
app/src/components/organizations/MakeOrganizationForm.tsx
app/src/components/profile/CompleteProfileCallout.tsx
app/src/components/profile/EditEmail.tsx
app/src/components/profile/GithubConnection.tsx
app/src/components/profile/GovForumConnection.tsx
app/src/components/profile/public/ProfileGithubProximity.tsx
app/src/components/profile/public/ProfileHeader.tsx
app/src/components/profile/public/ProfileHeaderLinks.tsx
app/src/components/profile/public/ProfileOrganizations.tsx
app/src/components/profile/public/ProfileProjects.tsx
app/src/components/profile/public/ProfileRoles.tsx
app/src/components/profile/public/ProjectWithLink.tsx
app/src/components/profile/public/PublicProfile.tsx
app/src/components/round/results/ProjectsList.tsx
app/src/components/round/results/ResultFilters.tsx
app/src/providers/LayoutProvider.tsx
app/tailwind.config.ts

Description:
This PR deals with abstraction of some of the components and making a mobile friendly version of public profiles.
Demo:
https://www.loom.com/share/b057d8c251d74ab696b3150e5ca8b0aa?sid=d169c773-0bd7-44db-bdf0-51c4f0ee3eb0

feat: components abstraction, public profiles rework

---

app/src/app/api/github/user/[username]/route.ts
app/src/app/globals.css
app/src/components/common/Badge.tsx
app/src/components/common/BubbleLink.tsx
app/src/components/profile/public/ProfileHeaderLinks.tsx
app/tailwind.config.ts

Issue: https://github.com/voteagora/op-atlas/issues/487

feat: public user profile discord badge

---

app/src/app/api/v1/projects/[projectId]/route.ts
app/src/db/projects.ts

Satisfies Issue https://github.com/voteagora/op-atlas/issues/484.

Bugfix: Delete Project repositories alongside Project

---

app/src/components/missions/details/ApplicationStatusCard.tsx
app/src/components/missions/details/EnrolledProjectsCard.tsx
app/src/components/missions/details/UserRoundApplicationStatusCard.tsx

Reopens the discussion for https://github.com/voteagora/op-atlas/issues/560.

Improve Application Status Card data formatting based on text

---

app/src/lib/actions/repos.ts
app/src/lib/github.ts

`verifyNpm` now traverses the entire repo directory tree to find valid `package.json` files and tests whether those are valid `npm` packages, rather than just using the top level `package.json` file, which doesn't work for monorepos. 
A note: this change affects the endpoint performance and doesn't perform particularly well in very large repos. It may be preferable to use something like `https://api.github.com/search/code?q=filename:package.json+repo:${owner}/${repo}` instead, or optimize requests to run in parallel (which would require the octokit rate limiting plugin).

fix: detecting npm package names in monorepos

---

app/src/components/home/Sidebar.tsx

Satisifies. https://github.com/voteagora/op-atlas/issues/578

Removed Past Round Rewards Banners on Homepage

---

app/src/components/missions/details/Eligibility.tsx
app/src/lib/MissionsAndRoundData.tsx

1. Update common eligibility text to remove "Dev Tooling" reference
2. Update eligible OP Chain text

Copy changes on mission page

---

app/prisma/migrations/20250213013802_contracts_v2_updates/migration.sql
app/prisma/schema.prisma
app/src/app/api/v1/projects/[projectId]/metadata_snapshot/route.ts
app/src/db/projects.ts
app/src/lib/actions/projects.ts
app/src/lib/actions/snapshots.ts
app/src/lib/eas.ts
app/src/lib/types.ts
app/src/lib/utils/metadata.ts

Integrate new EAS schema for VerifiedContracts

---

app/src/app/profile/verified-addresses/verified-address.tsx
app/src/components/profile/CompleteProfileCallout.tsx
app/src/db/users.ts

fix: issue-640 shorten address visually, not as prop

---

app/src/components/missions/application/ApplicationSubmitted.tsx
app/src/lib/actions/repos.ts
app/src/lib/github.ts

Issue: #653 
Document: https://www.notion.so/agoraxyz/Github-Fetching-Optimisation-1a4528b28fc480c8ae7df28fadf24cdb?d=1a4528b28fc480909040001c398e4d35#1a4528b28fc480cd8ffee7baf5f7e439

feat: issue 653 cache github requests

---

app/src/components/dashboard/UserProjectCard.tsx
app/src/components/missions/common/callouts/EnrolledCallout.tsx

fix: issue-569 ensure unique applications per roundId in UserProjectCard

---

app/src/components/dashboard/index.tsx
app/src/components/profile/CompleteProfileCallout.tsx

feat: dismiss complete user profile accordion

---

app/src/lib/actions/repos.ts
app/src/lib/github.ts

https://github.com/voteagora/op-atlas/issues/670

optimize github api requests: remove unnecessary calls. closes #670

---

app/src/components/common/Badge.tsx
app/src/components/projects/contracts/ContractFormField.tsx
app/src/components/projects/contracts/ContractsFormField.tsx
app/src/components/projects/contracts/DeployerFormField.tsx
app/src/db/projects.ts
app/src/lib/actions/contracts.ts
app/src/lib/oso.ts

feat: issue-654 add all contracts

---

app/src/app/dashboard/page.tsx
app/src/components/application/5/ApplicationFormTabs.tsx
app/src/components/application/5/ProjectImpactForm.tsx
app/src/components/application/6/ApplicationFormTabs.tsx
app/src/components/application/6/ProjectImpactForm.tsx
app/src/components/application/ProjectCard.tsx
app/src/components/dashboard/UserProjectCard.tsx
app/src/components/missions/application/ProjectApplication.tsx
app/src/components/projects/ProjectStatusSidebar.tsx
app/src/components/projects/grants/GrantsForm.tsx
app/src/components/projects/publish/PublishForm.tsx
app/src/components/projects/repos/ReposForm.tsx
app/src/db/projects.ts
app/src/hooks/db/useAdminProjects.tsx
app/src/hooks/db/useProjectDetails.tsx
app/src/lib/types.ts
app/src/lib/utils/index.ts
app/src/lib/utils/metadata.ts

The purpose of this PR is to solve out of memory problem produced by the bloated projects query

Reduce projects query size

---

app/src/app/api/v1/projects/[projectId]/metadata_snapshot/route.ts
app/src/app/projects/[projectId]/components/UnsavedChangesToast.Client.tsx
app/src/app/projects/[projectId]/contributors/page.tsx
app/src/app/projects/[projectId]/rewards/page.tsx
app/src/app/projects/new/page.tsx
app/src/components/dashboard/UserProjectCard.tsx
app/src/components/projects/ProjectSidebar.tsx
app/src/components/projects/ProjectStatusSidebar.tsx
app/src/components/projects/details/ProjectDetailsForm.tsx
app/src/components/projects/publish/PublishForm.tsx
app/src/components/projects/rewards/RewardAccordion.tsx
app/src/components/projects/rewards/RewardsSection.tsx
app/src/components/projects/teams/TeamForm.tsx
app/src/db/projects.ts
app/src/lib/actions/snapshots.ts
app/src/lib/actions/utils.ts
app/src/lib/hooks.ts
app/src/lib/types.ts
app/src/lib/utils/index.ts
app/src/lib/utils/metadata.ts

Overloaded `getProject` query throws `temporary file size exceeds temp_file_limit` error.
This PR breaks team into its own query

Break down project data query. Closes #726

---

app/src/app/project/[projectId]/components/Description.tsx
app/src/app/project/[projectId]/components/Header.tsx
app/src/app/project/[projectId]/components/IncreaseYourImpact.tsx
app/src/app/project/[projectId]/components/Mission/DevToolingMission.tsx
app/src/app/project/[projectId]/components/Mission/OnchainBuilderMission.tsx
app/src/app/project/[projectId]/page.tsx
app/src/components/common/ExtendedLink.tsx
app/src/components/common/SocialBadgeLink.tsx
app/src/components/common/TrackedExtendedLink.tsx
app/src/components/common/TrackedLink.tsx
app/src/components/round/results/ProjectsList.tsx

Improvements to project profiles analytics. Primarily focusing on tracking links

Project page analytics

---

app/src/db/users.ts
app/src/graphql/__generated__/types.ts
pnpm-lock.yaml

feat: tag contacts for retro funding

---

app/src/components/projects/rewards/DeliveryAddressVerificationForm.tsx

Governance delegation pledge #796

---

app/public/assets/icons/plus.svg
app/src/app/profile/verified-addresses/verified-address.tsx
app/src/components/dashboard/AddFirstProject.tsx
app/src/components/dashboard/MakeFirstOrganization.tsx
app/src/components/profile/CompleteProfileCallout.tsx

Icon alignment 

---

app/src/providers/LayoutProvider.tsx

Updated restricted routes and added support for wildcard matches

Desktop splash for recipients and projects #789

---

app/src/app/profile/verified-addresses/verified-address.tsx

https://www.loom.com/share/2c154e9d0b3d4358b6ef718b33f33841?sid=3e293811-a7af-47d7-93b3-0c67001dfebb

Hover on verified addresses #748

---

app/src/components/dashboard/MakeFirstOrganization.tsx
app/src/components/dashboard/index.tsx

Removed introducing orgs dialog + new badge #793

---

app/src/app/project/[projectId]/page.tsx

Issue #780 
**Note:** Part of it (section showing for all users) have already been implemented.

feat: issue-780 increase your impact redesign

---

app/src/components/home/Rounds.tsx

fix: issue-778 rm missions learn more

---

app/prisma/migrations/20250411182626_contact_email_tags/migration.sql
app/prisma/schema.prisma
app/src/app/api/tag-contacts/route.ts
app/src/db/users.ts

Description:
Added _**KYC Started & KYC Cleared**_ tags for mailchimp contacts. Reworked existing implementation and optimised it.
Issue: #483

feat: issue-483 KYC User tags

---

app/src/components/dialogs/AddGrantDeliveryAddressDialog.tsx
app/src/components/projects/rewards/AddGrantDeliveryAddressForm.tsx
app/src/db/organizations.ts

Issue: #790 
Demo:
https://www.loom.com/share/9583c87335fc462eb8a88addaef76f15

feat: auto assign all available projects to kyc org

---

app/src/components/dialogs/AddGrantDeliveryAddressDialog.tsx
app/src/db/organizations.ts
app/src/db/projects.ts
app/src/lib/actions/organizations.ts

Issue: #809 
Demo:
https://www.loom.com/share/2e39445f2ab747668a7f68d0282da777

feat: issue-809 unique constraint toast message

---

app/src/components/home/Rounds.tsx

Cleaned up imports and added z-index for the feedback button

Floating feedback button #785

---

app/src/db/kyc.ts

fix: issue-818 check for projectId instead of kycTeam id

---

app/src/components/projects/contracts/ContractsForm.tsx
app/src/components/projects/contracts/DefiLlamaFormFiled.tsx

fix: issue-811 empty state for defillama adapter

---

app/src/components/missions/application/ApplicationSubmitted.tsx

fix: issue-580 border radius in application submitted screen

---

app/src/db/users.ts
app/src/scripts/mailchimp-export.ts

feat: issue-826 add project ids to mailchimp export

---

app/src/lib/MissionsAndRoundData.tsx

Issue: https://github.com/voteagora/op-atlas/issues/895

Fix results link

---

app/src/app/project/[projectId]/components/Description.tsx
app/src/app/project/[projectId]/page.tsx
app/src/db/projects.ts

Issue: https://github.com/voteagora/op-atlas/issues/905

Project Profile: Link to Org

---

app/src/app/proposals/page.tsx
app/src/app/proposals/proposalsPage/components/ProposalCard.tsx
app/src/app/proposals/proposalsPage/components/standardProposals/Proposals.tsx
app/src/app/proposals/proposalsPage/components/standardProposals/StandardProposals.tsx

This can be condensed down into one branch. The separation is no longer needed.

921-governance-page-without-self-nomination-proposals

---

app/src/lib/oso/constants.ts

Updates mapping for chainName: chainId for S7 projects. 
Sources:
- https://atlas.optimism.io/missions/retro-funding-onchain-builders
- https://www.superchain.eco/chains
- https://chainlist.org/
- https://docs.opensource.observer/docs/integrate/datasets/#superchain

fix: chain mapping

---

app/src/app/citizenship/components/UserRequirements.tsx

Fixing qualification display for non-eligible users

Qualification display

---

app/src/app/citizenship/components/ActiveCitizen.tsx
app/src/app/citizenship/components/Sidebar.tsx
app/src/app/citizenship/components/UserRequirements.tsx
app/src/components/common/EligibleCitizenAvatar.tsx
app/src/hooks/citizen/useCitizenshipRequirements.ts
app/src/lib/constants.ts

- generalized qualifying user avatar
- refactored passport state displays

Citizenship app follow 

---

app/src/app/citizenship/components/UserRequirements.tsx
app/src/app/citizenship/page.tsx
app/src/db/citizens.ts
app/src/lib/actions/citizens.ts

- chains / apps can register even after users are limited 
- disabled user registrations
- added passport links (Shaun's request)

Registration hotfix 

---

app/src/lib/actions/citizens.ts

This PR adds test accounts to the s7 check.

Add test accounts

---

README.md
app/package.json
app/src/db/citizens.ts
app/src/lib/actions/citizens.ts
app/src/scripts/revoke-citizenship.ts

Revoking citizenship attestations by address `pnpm revoke:citizenship 0x123...456`

Revoking citizenship attestations 

---

app/src/app/citizenship/components/UserRequirements.tsx
app/src/hooks/citizen/useCitizenshipRequirements.ts
app/src/hooks/citizen/useS7Citizen.ts
app/src/lib/actions/citizens.ts

- removed s7 citizenship requirement
- decreased user citizens limit to 1000

Removing s7 citizenship requirement

---

app/src/app/citizenship/components/UserRequirements.tsx
app/src/components/common/Navbar.tsx
app/src/hooks/citizen/useCitizenshipRequirements.ts
app/src/hooks/citizen/useS7Citizen.ts
app/src/lib/actions/citizens.ts
app/src/lib/proposals.ts

1084-p0---subtext-under-proposal-title-on-the-governance-page-should-read-voters-citizens-delegates-the-comma-should-be-a-colon

---

app/src/components/proposals/proposal.types.ts
app/src/components/proposals/proposalPage/VotingSidebar/votingCard/VoterActions.tsx
app/src/components/proposals/proposalPage/VotingSidebar/votingCard/VotingCard.tsx
app/src/components/proposals/proposalPage/VotingSidebar/votingColumn/OverrideVoteCard.tsx
app/src/components/proposals/proposalPage/VotingSidebar/votingColumn/StandardVoteCard.tsx
app/src/components/proposals/proposalPage/VotingSidebar/votingColumn/VoteButton.tsx
app/src/components/proposals/proposalPage/VotingSidebar/votingColumn/VotingColumn.tsx
app/src/lib/utils/voting.ts

- Adds styling updates to button colors, spacing, and text.
- Utilizes existing shadcn button rather than custom button implementation

1120 Polish Voting Card Styling

---

app/src/components/proposals/proposalsPage/components/ProposalRow.tsx

Temp fix while a solution is worked on.

Temporarily show results as passed until a better solution worked in.

---

app/src/components/projects/repos/schema.ts
app/src/components/projects/teams/DeleteTeamMemberDialog.tsx

Handles issues https://github.com/voteagora/op-atlas/issues/206 + https://github.com/voteagora/op-atlas/issues/1071

URL validation + Fix weird text

---

app/src/components/profile/public/ProfileRoles.tsx

Fixes issue #1159 where vote attestations were incorrectly displayed on user profiles.

fix: filter out vote attestations from user profile

---

app/src/app/governance/roles/components/RoleRow.tsx
app/src/components/proposals/proposalsPage/components/ProposalCard.tsx

displaying past roles as "closed"

past roles label update

---

app/src/components/projects/contracts/ContractsForm.tsx
app/src/components/projects/details/ProjectDetailsForm.tsx
app/src/components/projects/grants/GrantsForm.tsx
app/src/components/projects/repos/ReposForm.tsx
app/src/components/projects/teams/TeamForm.tsx

This PR removed conditional navigation logic so Save button now advances to next step in all project setup forms.

fix: Save button now auto-advances to next step in project setup

---

app/src/components/proposals/proposalPage/VotingSidebar/VotingRedirect.tsx
app/src/components/proposals/proposalPage/VotingSidebar/VotingSidebar.tsx

Implements [this issue](https://github.com/voteagora/op-atlas/issues/1178)

Telegram support link for qualifying citizes #1178

---

app/src/lib/utils/voting.ts

patch fix null eligibility

---

app/src/components/common/Account.tsx
app/src/components/common/Navbar.tsx

* Hide username on mobile to make space on mobile for dropdown

Fix: Show profile dropdown menu on mobile

---

app/src/app/project/[projectId]/components/Header.tsx
app/src/components/home/RewardedProjectCrousel.tsx
app/src/providers/LayoutProvider.tsx

* Remove citizenship banner.
* Add bg if there is no thumbnail url for rewarded project
* Remove banner in projects page if there is no cover image
https://voteagora.atlassian.net/browse/OPAG-108
https://voteagora.atlassian.net/browse/OPAG-109

Fixes: Landing page.

---

app/src/components/proposals/proposal.types.ts
app/src/components/proposals/proposalPage/VotingSidebar/votingCard/VotingCard.tsx
app/src/components/proposals/proposalPage/VotingSidebar/votingColumn/CandidateCard.tsx
app/src/components/proposals/proposalPage/VotingSidebar/votingColumn/CandidateResult.tsx
app/src/components/proposals/proposalPage/VotingSidebar/votingColumn/VotingColumn.tsx
app/src/lib/utils/voting.ts

Makes changes to styling an accordance with [OPAG-105](https://voteagora.atlassian.net/jira/software/c/projects/ENG/boards/11?selectedIssue=OPAG-105)
[OPAG-105]: https://voteagora.atlassian.net/browse/OPAG-105?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OPAG-105-Visual-approval-elements

---

app/src/app/profile/organizations/[organizationId]/grant-address/components/GrantAddressForm.tsx
app/src/components/dialogs/AddGrantDeliveryAddressDialog.tsx
app/src/components/dialogs/SelectKYCProjectDialog.tsx
app/src/components/projects/rewards/CompletedGrantDeliveryForm.tsx

User reported address they add disappears after some amount of time and that they are no longer able to re-assign addresses. 
This PR adds more context to Superfluid receiving addresses for projects to provide more information to the user on why they cannot change the address after a stream has been created.
Additionally, it is confirmed the address associations for the KYOrganizations where not created. Additional error logging has been added to help aide in debugging if the situation is to arise again.

OPAG-139-Grant-Addresses

---

app/public/assets/icons/time-fill.svg
app/src/components/icons/remix.tsx
app/src/components/missions/details/Header.tsx
app/src/lib/utils/retroFundingDevToolingData.tsx
app/src/lib/utils/retroFundingOnchainBuildersData.tsx

* Update budget for onchain and dev tooling.
* Update info about season timeline.
* Add info about rollover rewards to next season.
* Remove unused time-fill icon.
* Add new remix time-fill icon.

Feat: Updates to retro funding grant pages.

---

app/src/scripts/create-mock-citizens.ts

Use this script to seed the dev db with mock Citizens data: 
`npx tsx src/scripts/create-mock-citizens.ts`

Seed Citizenship data

---

app/src/lib/actions/grantEligibility.ts

Modify KYB logic in submitGrantEligibilityForm to prevent cross-organization KYC user reuse. For organization-tied forms, check existing users by email, type, and organization relationship. For project-tied forms, always create new users.

fix(grant-eligibility): scope KYB user reuse to organizations

---

app/src/components/grant-eligibility/steps/SignersStep.tsx

Removed vestigial company from signers step. Does not affect KYB and is safe to remove.
businessName is nullable in KYCUser and can be removed with usertype.

Removed company from signers step.
