prisma/schema.prisma
src/components/dashboard/index.tsx
src/db/projects.ts
src/lib/actions/projects.ts

I think it makes sense to use attestationId as a default identifier for projects since all the projects will have a unique attestation. This also makes it easier to query the projects and removes the confusion between attestationId & projectId

use attestationId as projectId

---

prisma/schema.prisma
src/components/projects/contracts/ContractForm.tsx
src/components/projects/publish/PublishForm.tsx
src/components/projects/repos/GithubForm.tsx
src/components/projects/repos/VerifyGithubRepoDialog.tsx
src/components/ui/avatar.tsx
src/db/projects.ts
src/lib/utils/index.ts

- Add a new field on the project for the last metadata update timestamp
- Update this field when making changes to the project or related entities
- Surface a warning when a project has outdated snapshots
- In the future we'll also notify other places or via a toast, but the core functionality is there

Track last project update to surface unpublished changes

---

prisma/migrations/20240529214307_drop_application_constraint/migration.sql
prisma/schema.prisma
src/lib/actions/applications.ts
src/lib/actions/snapshots.ts

If a project has already submitted and application, but goes back and updates their metadata, then we want to publish both a metadata snapshot *and* a new application

Create a new application attestation and entry when publishing

---

src/app/application/page.tsx
src/app/projects/[projectId]/publish/page.tsx
src/lib/actions/applications.ts

Some teams were hitting issues when applying. There was evidence of a timeout in the Vercel logs, as well as a failure from EAS with a reverted transaction. Some mitigations:
- Bump timeout for application from 60 seconds to 120 (pretty large but we are sending txns in a loop...)
- Submit attestations sequentially rather than in parallel so we don't risk nonce collisions/reverts

Improve reliability of application submission

---

app/src/components/common/OutboundArrowLink.tsx
app/src/components/profile/public/ProfileRoles.tsx

Adds an about link to certain attestations that match a specific criteria that links to the optimism governance glossary.
Satisifies https://github.com/voteagora/op-atlas/issues/416.

Public Profile - Attestation Card - About Link

---

app/src/components/profile/public/ProfileHeaderLinks.tsx

Optionally renders the followers section for github and farcaster if the follower counts are present.

Public Profile - Github/Farcaster follower improvements

---

app/src/components/home/Rounds.tsx
app/src/components/missions/application/MissionApplication.tsx
app/src/components/missions/application/MissionApplicationTabs.tsx
app/src/components/missions/application/ProjectApplication.tsx
app/src/components/missions/details/Mission.tsx
app/src/components/missions/details/UserRoundApplicationStatusCard.tsx
app/src/hooks/db/useAdminProjects.tsx
app/src/hooks/db/useUserProjects.tsx
app/src/hooks/db/useUserRoundApplications.tsx

There was an issue where if a user's project was also a part of an organization, then it was excluded from the hook. Now we changed the hook grab all the projects that the user is an admin of.
Also lays the groundwork for more reusable components that improve testing/reusability.
Satisfies https://github.com/voteagora/op-atlas/issues/586.

Application status card improvements

---

app/src/components/missions/application/ProjectApplication.tsx
app/src/lib/MissionsAndRoundData.tsx

Adds a green checkmark if the user's project has an npm/crate repo.
*NOTE: This should not affect true eligibility. They should still be able to submit the project whether or not they have any associated npm/crate packages.
Satisfies https://github.com/voteagora/op-atlas/issues/591.

Jake/issue #591 green checkmark npm crate

---

app/src/lib/api/mailchimp.ts
app/src/lib/utils/index.ts
app/src/lib/utils/tags.ts

This came out as a talk with Emily - the idea is to keep the manually added tags from mailchimp and push on top of them

feat: keep existing mailchimp tags that dont exist in db

---

app/src/db/organizations.ts

Solves: https://github.com/voteagora/op-atlas/issues/717.
Adds the thumbnailUrl to an organization's project calls.

fix: adds thumbnailUrl to org project calls

---

app/src/app/project/[projectId]/components/Mission/index.tsx
app/src/app/project/[projectId]/page.tsx
app/src/db/projects.ts

Description:
Use project reward amounts on project profile page instead of data consumed from OSO Json files

fix: use project rewards amount on project profiles

---

app/src/components/organizations/MakeOrganizationForm.tsx

This pull request addresses the issue #800 , where the "+Add" button was visible before any initial link was input in the Organization settings form. As said in the issue this could lead to user confusion, as they might think they need to click "+Add" to save the link they've input. The changes ensure that the "+Add" button only appears after a link is input, aligning the behavior with the Project Settings form.
**Changes Made:**
- Added helper functions `shouldShowWebsiteAdd` and `shouldShowFarcasterAdd` to determine the visibility of the "+Add" button based on whether the last field has content.
- Updated the rendering logic for the "+Add" buttons in the form to utilize these helper functions, ensuring they only appear when appropriate.
**Impact:**
- Improves user experience by reducing …

Fix #800: Display "+Add" Button Only After Input in Organization Form

---

app/src/app/api/cron/persona/route.ts
app/src/lib/persona.ts

This PR speeds up Persona inquiries & cases processing by parallelizing processing at expense of increased memory consumption. 
Before: each batch is processed one at a time. Once processed, cache is cleared
After: each batch is processed in parallel with other batches. Once processed, cache is cleared. Memory consumption is significantly higher due to parallel processing. 
Batch size `~12KB`
Next memory limit: `3009 MB`
We'll hit memory limit at `~250K` batches. Realistically, there're will be way less than `100` batches processing simultaneously at any given moment -- so we're well within the limits

Persona CRON speedup

---

app/src/components/profile/public/ProjectWithLink.tsx

Issue: https://github.com/voteagora/op-atlas/issues/844
There is an open question here: I am guessing # 1 but feels worth it to check before merging
Should we hide the project from the profile if `project.applications.length === 0` (What this PR is currently doing)
OR
Still link to the project id anyway?

User profiles show projects that don't have project-profiles

---

app/src/components/common/chain.ts
app/src/components/projects/contracts/VerifyAddressDialog.tsx

Issue: https://github.com/voteagora/op-atlas/issues/736
Fixed only for chains using Etherscan or Routescan. Blockscout doesn't support the /verifiedSignatures (or similar) page we use.
Looked for an alternative/similar solution in Blockscout and couldn't find any.

Correct etherscan network

---

app/src/components/common/Account.tsx

#Closes #1035
**Changes:**
- updated text size to 14px with 20px line-height and primary-foreground color
- updated to py-2.5 (10px top-bottom) while keeping px-4 (16px left-right)
- removed fixed width constraint to allow natural button sizing based on content and padding
- height: kept h-10 (40px) as specified
The button should now appear at the proper default size with the correct text styling and spacing as specified in your requirements

Topbar sign in button needs polish

---

app/src/components/dialogs/AddGrantDeliveryAddressDialog.tsx
app/src/components/projects/rewards/AddGrantDeliveryAddressForm.tsx
app/src/components/projects/rewards/DeliveryAddressVerificationForm.tsx
app/src/db/kyc.ts
app/src/lib/actions/organizations.ts
app/src/lib/actions/projects.ts

This PR fixes Grant Delivery Address Flow Issues
- **Start Over button was non-functional** - existed but had empty implementation
- **Address validation occurred too late** - after signature step, causing addresses to disappear
- **Poor error handling** - confusing "already KYC'd" messages and form data loss
- **Addresses became unusable** - validation considered soft-deleted KYC teams
- **Implement functional Start Over button** - properly deletes KYC teams and resets process
- ** Add early address validation** - check availability before signature step
- ** Preserve form data on errors** - maintain user input when validation fails
- ** Improve error messages** - clear, actionable feedback for duplicate addresses
- ** Fix validation logic** - only consider active KYC teams (`deletedAt: …

fix: add grant address organization

---

app/src/components/home/SupportedChains.tsx

Implements a suggested change to the animation of SupportedChains desktop component which is a bit smoother. When I was on the existing homepage, I found the animation to be quite snappy and aggressive, so I implemented a bit of a softer "mac-os dock" type animation. 
No pressure to merge it, but I wanted to contribute it anyways :)
Demo
https://github.com/user-attachments/assets/ff0f78fa-598f-4cbc-bed3-f2b9e8db6322

SupportedChains animation suggestion

---

app/codegen.ts

This PR loads the .env file before graphql code-gen, allowing the script to pick up `OSO_AUTH_TOKEN` properly on our local.

Load dot env

---

app/src/components/proposals/proposalPage/VotingSidebar/votingColumn/VotingColumn.tsx

Possible fix for vote values not being included in the mixpanel event.

Split key:value pairs when recording fails only for value.

---

app/src/db/projects.ts

Will now only return projects with published snapshot data.

Update project metadata to return only for published projects

---

app/src/components/profile/GovForumConnection.tsx

Ensured that GovForum URLs accept `.eth`

Allow dots (.eth) in GovForum URLs
